# Generated by Django 5.2.2 on 2025-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_article_twitter_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="twitter_data",
        ),
        migrations.AlterField(
            model_name="article",
            name="identifiers",
            field=models.JSONField(),
        ),
    ]
