# Generated by Codex
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20250604_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='identifiers',
            field=models.JSONField(),
        ),
    ]
