# Generated by Django 3.1 on 2025-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_article_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
