# Generated by Django 3.0.6 on 2020-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200530_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
    ]
