# Generated by Django 3.0.6 on 2020-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_preference',
        ),
        migrations.AddField(
            model_name='user',
            name='authors',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
    ]
