# Generated by Django 3.1 on 2025-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20210128_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
